version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: decameron_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: decameron_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

